spring:
  datasource:
    url: ${DB_URL}
logging:
  level:
    root: WARN
    com.sementelivre.backend: INFO
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: never
